## The demo session's flow window — read from the REAL recorded container.
##
## ## Why this one is not fixture data
##
## `demo_session.nim` is explicit that everything about the *replay* is fixture:
## the position, the call frames, the variable values, the event stream. It has
## to be, because producing them means running a replay engine and
## `static_export.nim` is a Nim compile with no browser anywhere near it.
##
## The values overlay is the one part of that where a plausible-looking
## invention would be indistinguishable from the truth *and* would be the
## product's headline claim. So it is not invented. `flow.json` beside the
## sources is generated by `client/fixtures/demo-session/extract-flow.mjs` from
## `fixtures/trace/noir_space_ship/zk_shields.ct` — the real CTFS container
## `nargo trace` produced — and every number in it is a number the recorder
## wrote. The extraction is committed rather than described so the claim can be
## re-run:
##
##     ct-print --full fixtures/trace/noir_space_ship/zk_shields.ct > /tmp/zk.json
##     node client/fixtures/demo-session/extract-flow.mjs /tmp/zk.json \
##       > client/fixtures/demo-session/flow.json
##
## That is also why `fixtureState`'s numbers can be cross-checked against it
## rather than merely agreeing by construction: `test_debug_route` asserts the
## Values pane and the overlay report the same `damage`, `mass`, `shield_pct`
## and `remaining_shield` at the same coordinate, so the two producers cannot
## drift into telling one reader two things.
##
## ## What the window covers, and where it stops
##
## The first `iterate_asteroids` call and everything it invoked inside
## `src/shield.nr`, cut at the session's position. The cut is the honesty
## constraint made mechanical: the served page is a still frame at one
## coordinate, and a pass the session has not reached has no values AT THAT
## COORDINATE. The passes it HAS completed are carried in full — pass 0 and
## pass 1 ran to the end before the session entered pass 2 — which is what the
## iteration rail reaches and what makes it worth having.
##
## `src/main.nr` gets no window. The session's frame there is `main`, suspended
## mid-call on line 15; every value the trace records for the lines after it is
## a value that does not exist yet at this coordinate. A window per file is also
## what `FlowLayoutWindow` models, its `sourceLines` being one file's text.

import std/[json, os, strutils]

import ./flow_view

const
  FlowJson* = staticRead(
    currentSourcePath().parentDir.parentDir.parentDir /
    "fixtures" / "demo-session" / "flow.json")
    ## Read at COMPILE time, like `symbols.json` and the source files beside it,
    ## so the built exporter needs no fixture directory next to it.

proc valueList(node: JsonNode): seq[FlowValueText] =
  ## A `{name: rendered}` object as the layout module's value list.
  ##
  ## Text and not a structured value on purpose: `FlowValueText`'s own header
  ## says layout needs the WIDTH and the IDENTITY of a value and never its
  ## structure. The recorder's decoded shape was rendered once, by the
  ## extractor, against the container — so nothing here can render `10000` two
  ## ways.
  if node.isNil or node.kind != JObject: return
  for name, value in node:
    if value.kind == JString:
      result.add FlowValueText(expression: name, text: value.getStr)

proc strings(node: JsonNode): seq[string] =
  if node.isNil or node.kind != JArray: return
  for item in node:
    if item.kind == JString: result.add item.getStr

proc demoFlowInput*(sourceText: string): FlowWindowInput =
  ## The recorded window, ready for `flow_view.applyFlow`.
  ##
  ## `sourceText` is passed in rather than read again here: `demo_session.nim`
  ## already holds `src/shield.nr` and a second `staticRead` of the same file
  ## would be a second copy that could be given a different path.
  let document = parseJson(FlowJson)
  result.path = document{"path"}.getStr("")
  result.locationTicks = document{"position"}{"ticks"}.getInt(0)

  var lines: seq[string] = @[]
  for line in sourceText.replace("\r\n", "\n").split('\n'):
    lines.add line
  if lines.len > 0 and lines[^1].len == 0: lines.setLen(lines.len - 1)

  let loopNode = document{"loop"}
  let iterationTicks = block:
    var ticks: seq[int] = @[]
    let node = loopNode{"iterationTicks"}
    if not node.isNil and node.kind == JArray:
      for tick in node: ticks.add tick.getInt(0)
    ticks

  # Index 0 is the backend's placeholder `Loop::default()`. It is not a loop and
  # never has been: `computeFlowLayout` starts its scan at 1 and `pickFocusedLoop`
  # skips it. Reproducing the placeholder rather than shifting every index by one
  # is what keeps this window the same shape as the engine's, so the static frame
  # and a hydrated one are laid out by the same code with the same indices.
  var loop = FlowLayoutLoop(
    first: loopNode{"first"}.getInt(0),
    last: loopNode{"last"}.getInt(0),
    registeredLine: loopNode{"registeredLine"}.getInt(0),
    rrTicksForIterations: iterationTicks,
    stepCounts: @[],
    iterationSteps: @[])
  for _ in 0 ..< iterationTicks.len:
    loop.iterationSteps.add @[]

  var steps: seq[FlowLayoutStep] = @[]
  var functionLabel = ""
  var stepNodes = document{"steps"}
  if stepNodes.isNil or stepNodes.kind != JArray: stepNodes = newJArray()
  for node in stepNodes:
    let iteration = node{"iteration"}.getInt(-1)
    let line = node{"line"}.getInt(0)
    let inLoop = iteration >= 0
    if line == loop.registeredLine and functionLabel.len == 0:
      functionLabel = node{"function"}.getStr("")
    let index = steps.len
    steps.add FlowLayoutStep(
      stepCount: node{"ticks"}.getInt(0),
      line: line,
      loopIndex: (if inLoop: 1 else: 0),
      iteration: max(iteration, 0),
      rrTicks: node{"ticks"}.getInt(0),
      exprOrder: strings(node{"order"}),
      beforeValues: valueList(node{"before"}),
      afterValues: valueList(node{"after"}))
    if inLoop:
      loop.stepCounts.add index
      if iteration < loop.iterationSteps.len:
        loop.iterationSteps[iteration].add (line: line, stepCount: index)
    if node.hasKey("returns"):
      result.returns.add FlowReturn(
        line: line,
        iteration: (if inLoop: iteration else: NoIteration),
        text: node{"returns"}.getStr(""))

  result.functionLabel = functionLabel
  result.window = FlowLayoutWindow(
    steps: steps,
    loops: @[FlowLayoutLoop(), loop],
    sourceLines: lines,
    tabSize: 4)
