## rehearse/coverage.nim — the **coverage contract** a rehearsal is measured
## against, and the ledger that records what a run actually exercised.
##
## ## Why a contract and not a size
##
## A rehearsal's value is COVERAGE, NOT VOLUME, and that is a measurement and
## not an opinion. On 2026-09-28 a **290-object** rehearsal of the demo tree
## passed cleanly and a **460,589-object** one then found a data-loss defect —
## and the difference between them was not the 460,299 objects. It was that the
## small one had **one chain**, and one chain cannot overwrite another chain's
## registry row. The bug needed **cardinality ≥ 2**. It did not need scale, and
## no amount of scale on one chain would ever have reached it.
##
## So "partial" here does not mean "smaller and we hope that is enough". It
## means **selected to satisfy an explicit contract**, and a run that does not
## satisfy the contract **fails** rather than reporting a percentage. A number
## printed at the end of a green run is read by nobody; a refusal is read by
## whoever has to make it go away.
##
## ## The five dimensions, and where each comes from
##
## Every cell is DERIVED from the system rather than listed by hand wherever
## that is possible, because a hand-written list is a second source of truth
## that goes stale exactly when a new case is added — which is the moment the
## list mattered.
##
##   `class`       one cell per member of `publisher.ObjClass`, generated by
##                 iterating the enum. A class added to `classOf` becomes a
##                 required cell with nobody remembering to add it, and a
##                 rehearsal over a tree that emits none of it fails by name.
##
##   `strategy`    one cell per member of `publisher.Strategy`, same derivation.
##                 Implied by `class` today; stated separately because the
##                 class→strategy map is itself a thing that can change, and
##                 when it does the two dimensions stop agreeing, which is the
##                 signal.
##
##   `cardinality` the singletons. A cell here exists wherever ONE of something
##                 cannot exhibit a failure that TWO can: two chains (the
##                 registry row), two generations, two index shards, two
##                 address ranges. This is the dimension the 290-object
##                 rehearsal was blind on, and it is written down so that
##                 blindness is a red line rather than a thing nobody thought
##                 to check.
##
##   `branch`      BOTH SIDES of every conditional on the publish path.
##                 `putIfAbsent` won and lost; key-existence hit and missed;
##                 content-hash equal and differing; refresh same and
##                 superseded; the pointer flip halted and completed; the bulk
##                 confirmation satisfied and refused. A conditional exercised
##                 on one side only is a conditional whose other side has never
##                 run in this configuration, which is where an impedance
##                 mismatch lives.
##
##   `invariant`   the whole-system properties, each required in BOTH
##                 directions — accepting a legitimate tree AND refusing an
##                 illegitimate one. A guard proven only in the refusing
##                 direction is half-tested, and a guard that refuses the good
##                 path is the more expensive failure of the two: it blocked a
##                 legitimate publish twice on 2026-09-28.
##
## ## The cells are stated over OUTCOMES, not over procedure names
##
## The `invariant` cells deliberately do not name `assertRegistryKeepsKnownChains`
## or `assertNoUnknownGlobalPointer`. Those are one implementation of one of
## these invariants, they are not on `dev` at the time of writing, and a contract
## that names them would measure nothing on a tree published by anything else.
## What must be true is a property of the STORE after a sequence of publishes:
## no global object may stop naming a chain the store still holds data for. A
## publisher that refuses such a tree satisfies it; a publisher that merges
## correctly satisfies it; a publisher that writes and loses a row does not.
## That is checkable against any producer, including one written outside this
## repository, which is what makes the contract chain-agnostic and
## implementation-agnostic at the same time.

import std/[algorithm, sequtils, strutils, tables]

import ../publish/publisher

type
  Dimension* = enum
    dimClass = "class"
    dimStrategy = "strategy"
    dimCardinality = "cardinality"
    dimBranch = "branch"
    dimInvariant = "invariant"

  Cell* = object
    ## One required observation. `why` is not decoration: an unmet cell prints
    ## it, and a reader who meets `cardinality/chains-in-separate-trees` with no
    ## sentence beside it has to go and find out why two is the number.
    dim*: Dimension
    name*: string
    why*: string
    hits*: int
    witness*: string    ## the first concrete thing that exercised it

  CoverageLedger* = object
    cells*: OrderedTable[string, Cell]

func cellId*(dim: Dimension, name: string): string = $dim & "/" & name

proc add(l: var CoverageLedger, dim: Dimension, name, why: string) =
  l.cells[cellId(dim, name)] = Cell(dim: dim, name: name, why: why)

proc contractLedger*(): CoverageLedger =
  ## The contract. Everything derivable is derived.
  result.cells = initOrderedTable[string, Cell]()

  # ── class: generated from the enum, so `classOf` gaining a class gains a cell
  for c in ObjClass:
    result.add(dimClass, $c,
      "`publisher.classOf` can emit this class. A rehearsal that writes none " &
      "of it has never run this class's upload strategy against this store, " &
      "so nothing here has been measured about it — including whether the " &
      "store accepts the key shape at all.")

  # ── strategy: likewise
  for s in Strategy:
    result.add(dimStrategy, $s,
      "One of the three upload strategies in Publishing-And-Caching §2.1. " &
      "Implied by the classes today; stated separately because the " &
      "class→strategy map can change, and the two dimensions disagreeing is " &
      "the signal that it has.")

  # ── cardinality: every singleton that a second instance could clobber
  result.add(dimCardinality, "chains-in-separate-trees",
    "TWO chains, arriving as TWO independent producer trees published in " &
    "sequence into one store. This is the exact shape that lost data on " &
    "2026-09-28: `registry/**` is a GLOBAL key under the unconditional-rewrite " &
    "strategy, each single-chain tree carries a registry naming only its own " &
    "chain, and the second publish overwrote the first. One chain cannot " &
    "exhibit it at any scale.")
  result.add(dimCardinality, "chains-in-store",
    "Two chains present in the store at once, so a cross-chain regression has " &
    "something to regress against.")
  result.add(dimCardinality, "generations",
    "Two generations for some chain. A single generation cannot show that " &
    "`d/{chain}/g/{gen}/**` is immutable at its path while `current.json` " &
    "moves, nor that an old generation survives the flip.")
  result.add(dimCardinality, "index-shards",
    "Two `idx/**` shards. One shard cannot show that a shard is addressed by " &
    "its own path rather than by being the only one.")
  result.add(dimCardinality, "address-ranges",
    "Two `d/{chain}/seg/**` ranges. Ranges never change once written, so a " &
    "single range cannot show that a second one is added rather than " &
    "replacing it.")

  # ── branch: both sides of every conditional on the publish path
  result.add(dimBranch, "lease/acquired",
    "`putIfAbsent` WON — the single-writer lease was taken. The `/dev/stdin` " &
    "defect made this return false on an empty bucket, in every state, on " &
    "every store, and reported it as contention.")
  result.add(dimBranch, "lease/refused",
    "`putIfAbsent` LOST — a second publisher was refused while the lease was " &
    "held. Untested, a broken CAS is indistinguishable from a working one.")
  result.add(dimBranch, "key-existence/miss",
    "A content-addressed object was absent and was uploaded.")
  result.add(dimBranch, "key-existence/hit",
    "A content-addressed object was present and was SKIPPED. §2.3's " &
    "idempotency contract is that a re-run uploads zero; only the hit side " &
    "measures it.")
  result.add(dimBranch, "content-hash/equal",
    "An input-addressed `/t/**` object was present with MATCHING bytes and was " &
    "skipped — the ordinary case, and the one a determinism check must not " &
    "raise on.")
  result.add(dimBranch, "content-hash/differs",
    "An input-addressed `/t/**` object was present with DIFFERENT bytes: a " &
    "determinism incident (§2.8a). It must be reported, the object must NOT be " &
    "overwritten, and the command must exit 3.")
  result.add(dimBranch, "refresh/unchanged",
    "`--refresh` compared a stored object against the tree and found them " &
    "equal, so it skipped. This is the side that keeps the refresh cheap.")
  result.add(dimBranch, "refresh/superseded",
    "`--refresh` found the stored bytes DIFFERENT and rewrote them. Without " &
    "this path a producer fix never reaches a store that already holds the " &
    "wrong object, because the key did not move.")
  result.add(dimBranch, "flip/halted",
    "A cycle interrupted BEFORE the visibility flip left unreferenced content " &
    "and a `current.json` still naming the previous generation (§2.3).")
  result.add(dimBranch, "flip/completed",
    "A cycle that ran to the end flipped `current.json` last, after every " &
    "object it can reference was in place (§2.2).")
  result.add(dimBranch, "bulk-confirm/satisfied",
    "The post-transfer listing confirmed every key `putMany` was handed, so " &
    "the pointer flip was allowed to proceed.")
  result.add(dimBranch, "bulk-confirm/refused",
    "The post-transfer listing did NOT confirm a key, and the pointer flip was " &
    "refused. A bulk transfer moves many objects under one exit code; without " &
    "this side, the flip advertises a generation on the strength of a " &
    "process's exit status — the shape that put a pointer at head 74399 over a " &
    "height map that stopped at 74099.")

  # ── invariant: whole-system properties, both directions each
  result.add(dimInvariant, "global-pointer-no-chain-loss/refuses",
    "After publishing a tree that knows only ONE chain into a store that holds " &
    "TWO, no global (chain-less) object may have stopped naming the other " &
    "chain. Satisfied by refusing the publish, or by merging correctly — and " &
    "NOT satisfied by writing and losing a row, which leaves that chain's " &
    "objects present in the store and invisible to every reader. Stated over " &
    "the store's contents so it holds for any producer.")
  result.add(dimInvariant, "global-pointer-no-chain-loss/accepts",
    "A LEGITIMATE whole-site tree — one that knows every chain the store holds " &
    "— must publish SUCCESSFULLY. The refusing direction alone is half a test, " &
    "and it is the cheaper half: a guard that refuses the good path stops the " &
    "pipeline, and did so twice on 2026-09-28.")
  result.add(dimInvariant, "every-object-is-published/holds",
    "After a complete cycle over every chain the corpus declares, EVERY object " &
    "in the corpus is in the store. `publishChain` selects the keys a chain " &
    "owns with a `belongs` predicate, and an object that predicate admits for " &
    "no chain is an object the producer wrote and the publisher will never " &
    "upload — a hole with no error, no warning and no exit code, visible only " &
    "by subtracting the store from the tree.")
  result.add(dimInvariant, "resume-without-gap/holds",
    "A killed cycle re-run against the same store resumes from the published " &
    "`current.json`, uploads no duplicate, and ends with the pointer at the " &
    "generation the tree names (Pipeline-Architecture §3.2a).")
  result.add(dimInvariant, "idempotent-recycle/holds",
    "Re-running a completed cycle uploads ZERO content objects (§2.3). This is " &
    "a correctness contract as much as a cost one: an object rewritten on a " &
    "re-run is an object whose identity is not what the key says it is.")

proc record*(l: var CoverageLedger, dim: Dimension, name, witness: string) =
  ## Record one observation. Recording a cell the contract does not contain is
  ## a programming error and is loud rather than silent — a scenario that
  ## believes it is covering something the contract never asked for is a
  ## scenario whose author and the contract disagree.
  let id = cellId(dim, name)
  if id notin l.cells:
    raise newException(KeyError,
      "rehearsal recorded coverage for '" & id & "', which is not a cell of " &
      "the contract. Either add the cell to `contractLedger()` with the " &
      "property it defends, or fix the scenario's spelling.")
  l.cells[id].hits.inc
  if l.cells[id].witness.len == 0:
    l.cells[id].witness = witness

proc recordKeys*(l: var CoverageLedger, keys: openArray[string], witness: string) =
  ## Every key written in a scenario contributes its class and its strategy.
  for k in keys:
    let c = classOf(k)
    l.record(dimClass, $c, witness & ": " & k)
    l.record(dimStrategy, $strategyOf(c), witness & ": " & k)

func unmet*(l: CoverageLedger): seq[Cell] =
  for _, c in l.cells:
    if c.hits == 0: result.add c

func met*(l: CoverageLedger): int =
  for _, c in l.cells:
    if c.hits > 0: inc result

proc renderTable*(l: CoverageLedger): string =
  ## WHAT WAS EXERCISED, as a table, with the witness that exercised it.
  ##
  ## The witness column is the part that matters and the part a percentage
  ## cannot carry: `class/ocTraceContainer  1  A1: t/1f/…/trace.ct` is a claim
  ## somebody can go and check, while "97% covered" is a claim about a
  ## denominator nobody has seen.
  var rows: seq[(string, string, string, string)] = @[]
  var wId = 4
  for id, c in l.cells:
    let hits = if c.hits == 0: "—" else: $c.hits
    var w = c.witness
    if w.len > 72: w = w[0 ..< 69] & "..."
    rows.add (id, (if c.hits == 0: "MISS" else: "ok"), hits, w)
    wId = max(wId, id.len)
  var s = ""
  s.add "  " & "cell".alignLeft(wId) & "  st    hits  witness\n"
  s.add "  " & repeat('-', wId) & "  ----  ----  " & repeat('-', 40) & "\n"
  for (id, st, hits, w) in rows:
    s.add "  " & id.alignLeft(wId) & "  " & st.alignLeft(4) & "  " &
          hits.alignLeft(4) & "  " & w & "\n"
  s

proc renderUnmet*(l: CoverageLedger): string =
  ## The refusal. One paragraph per unmet cell, each carrying the property that
  ## went unmeasured, because "coverage 41/45" tells the reader to go and find
  ## four things and this tells them what they are.
  let miss = l.unmet()
  if miss.len == 0: return ""
  var s = "\nCOVERAGE NOT MET — " & $miss.len & " of " & $l.cells.len &
          " contract cells were never exercised.\n" &
          "A rehearsal is trusted because nothing is untouched, not because it " &
          "is large. These\nwere untouched:\n\n"
  for c in miss:
    s.add "  ✗ " & cellId(c.dim, c.name) & "\n"
    for line in c.why.splitLines():
      s.add "      " & line & "\n"
    s.add "\n"
  s

func findingIds*(l: CoverageLedger): seq[string] =
  ## Stable ids for the unmet cells, for the known-findings register.
  result = l.unmet().mapIt(cellId(it.dim, it.name))
  result.sort()
